config/routes.rb
Rails.application.routes.draw do
  get 'page/home'

  get 'page/about'

  get 'page/contact'

  devise_for :users

  resources :photos do
   resources :users
     member do
       post :share_photo
     end
   end

  resources :users do
    resources :photos
  end

  root 'photos#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  
  has_and_belongs_to_many :users
  validates :title, :presence => true
  has_attached_file :image, styles: { large: "600 x 600", medium: "300 x 300", thumb: "150 x 150"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_and_belongs_to_many :photos
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :current_password) }
    end
end

app/controllers/page_controller.rb
  class PageController < ApplicationController

  before_action :authenticate_user!, only: [:contact, :about]
    def home
    end

    def about
    end

    def contact
    end
  end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.all
    render :index
  end

  def show
    @photo = Photo.find(params[:id])
    render :show
  end

  def new
    @photo = Photo.new
    render :new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to  photos_path
    else
      render :new
    end
  end
  
  def share_photo
   @photo = Photo.find(params[:id])
   @user = User.find(params[:user_id])
   @photo.users << @user
   redirect_to :back
 end



  private
  def photo_params
    params.require(:photo).permit(:title, :description, :image, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @photo = Photo.find(params[:photo_id])
    @user = @photo.users.new
  end
  def create
    @photo = Photo.find(params[:photo_id])
    @user = @photo.users.new(user_params)
    if @user.valid?
     @photo.users << @user
      redirect_to photo_path(@photo)
    else
      render :new
    end
  end

  def edit
     render:new
  end

  def update
    @photo = Photo.find(params[:photo_id])
    @user = @photo.users.new(user_params)
    if @user.update(user_params)
      redirect_to photo_path(@photo)
    else
      render:new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @photo = Photo.find(params[:photo_id])
    @user = @photo.users.new(user_params)
    @user.destroy
    redirect_to photos_path
  end
private
  def user_params
    # params.require(:user).permit(:username, :user_ids => [], :photo_id)
    params.require(:user).permit(:username, :user_ids, :photo_id)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Photo-Share</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right" >
        <div align ="right">
          <% if user_signed_in? %>
          <%= link_to "Sign_out", destroy_user_session_path, method: :delete %>
          <% else %>
          <%= link_to "Sign_in", new_user_session_path %>
          <%= link_to "Sign_up", new_user_registration_path %>
          <% end %>

          <%= link_to "About", page_about_path %>
          <%= link_to "Contact", page_contact_path %>
        </div>
      </ul>
      <ul class="nav navbar-nav navbar-right">

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoShareRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <div class="container-fluid">
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
   </div>
   <%= yield %>
</body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/photos/_form.html.erb
  <div class="container">
      <div class="column-center">
        <%= form_for @photo, {multipart: true} do |f| %>
          <%= f.label :image %><br>
          <%= f.file_field :image %><br>
          <%= f.label :title %><br>
          <%= f.text_field :title %><br>
          <%= f.label :description %><br>
          <%= f.text_field :description %>

          <%= f.submit  %>
        <% end %>
      </div>
    <div class="column-left">



    </div>
  </div>

app/views/photos/_user_select.html.erb
<div class= "control-group">
  <%= form_tag share_photo_photo_path(@photo) do |f| %>
    <label> Users </label>
    <div class = "controls">
      <%= select_tag :user_id, options_for_select(User.all.map{|u| [u.username, u.id]}) %>
    </div>
      <%= submit_tag "Add"  %>
  <% end %>
</div>

app/views/photos/edit.html.erb
<%= render "form" %>

app/views/photos/index.html.erb
  <div class="container">
    <div class="column-center">
      <ul>
        <% @photos.each do |photo| %>
          <li>
            <%= link_to photo.title, photo_path(photo) %><br>
            <%= image_tag photo.image.url(:medium) %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="column-left">
      <%= link_to "Upload your image", new_photo_path %>
    </div>
  </div>

app/views/photos/new.html.erb
<h1>Upload Image</h1>
<%= render "form" %>
<p><%= link_to "Home", photos_path %></p>

app/views/photos/show.html.erb
<div class="container">
  <div class="column-center">
    <h1><%= @photo.title %></h1>
    <%= image_tag @photo.image.url(:large) %>
    <p><%= @photo.description %></p>
  </div>

  <div class="column-left">
  </div>

  <div class = "column-right">
    <%= render "user_select"%>
     <% @photo.users.uniq.each do |user| %>
      <li>
        <%= link_to user.username ,user_path(user)  %>
      </li>
    <% end %>


    <p align="center"><%= link_to "Edit Photo", edit_photo_path(@photo) %></p>
    <p align="center"><%= link_to "Delete Photo", photo_path(@photo),
                             :data => {:confirm => "You sure?",
                                       :method => "delete"} %></p>
  </div>

</div>

app/views/users/_form.html.erb
<%= render('layouts/errors', :object => @user) %>

<div class= "container">
  <%= form_for [@photo, @user] do |f| %>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
    <%= f.label :password %><br>
    <%= f.text_field :password %>

    <p><%= f.submit %></p>
  <% end %>
<div>

app/views/users/new.html.erb
<h1>Tag New User</h1>

<%= render "form" %>

app/views/users/show.html.erb
<div class=container>
  <div class = "column-center">

    <h4> Photos for <%= @user.username %> /h4><hr>
    <ul>
       <% @user.photos.uniq.each do |photo| %>
        <li>
          <%= link_to photo.title, photo_path(photo) %>
          <%= image_tag photo.image.url(:thumb) %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class ="column-left">
    <div class ="col-md-4">

    </div>
  </div>
  <div class = "column-right">
    <p align="center"><%= link_to "Edit Tag", edit_user_path(@user) %></p>
    <p align="center"><%= link_to "Delete Tag", user_path(@user),
                             :data => {:confirm => "You sure?",
                                       :method => "delete"} %></p>
  </div>